### PR TITLE
PG17 Support

### PR DESCRIPTION
**Pull request by philkra**
Imported through https://github.com/timescale/timescaledb-toolkit/pull/819 /cc @Jo0

### CODE REVIEW

**Comment by syvb** [comment]
The latest pgrx requires 1.82; you need to bump the Rust toolchain version.

**Comment by Jo0** [comment]
#821 to bump toolchain to 1.82.0

**Comment by graveland** [comment]
pgrx's upstream is using 1.81.0... are we sure 1.82.0 is required?

**Comment by Jo0** [comment]
Shame I can't make commits directly to the branch. Could you try with it bumped to 1.82?

**Comment by graveland** [comment]
> Shame I can't make commits directly to the branch. Could you try with it bumped to 1.82?

Pushed again with 82, It's the same error for 81 and 82:
```
error[E0658]: use of unstable library feature 'result_option_inspect'
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-bindgen-0.12.6/src/build.rs:114:19
    |
114 |         enum_name.inspect(|name| match name.strip_prefix("enum").unwrap_or(name).trim() {
    |                   ^^^^^^^
    |
    = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information
```

**Comment by Jo0** [comment]
I'm curious now if we are even using the correct image for running the tests.

**Comment by graveland** [comment]
I haven't actually tested it locally- if you have, and it works, it sounds like purely a CI issue unfortunately.

**Comment by graveland** [comment]
Confirmed: CI is attempting to build with rustc: 1.74.0 (79e9716c9 2023-11-13)

**Comment by Jo0** [comment]
I think I see what's going on with the image build and tagging now. Seems the [default tag](https://github.com/timescale/timescaledb-toolkit/blob/beac6d58a1077e082824083b19c0d216cefad5f6/.github/workflows/ci_image_build.yml#L15) for these runs are `timescaledev/toolkit-builder-test`, but the image tag being pulled for these CI Tests are tagged `timescaledev/toolkit-builder` [Example](https://github.com/timescale/timescaledb-toolkit/actions/runs/11485532463/job/31965834293?pr=820#step:2:19) 



```
  workflow_dispatch:
    inputs:
      tag-base:
        description: 'Push image to DockerHub with this base tag (remove "-test" enable)'
        required: false
        # Repeating the default here for ease of editing in the github actions form.  Keep in sync with below.
        default: timescaledev/toolkit-builder-test
```

Do we need to do a manual run of `Build CI Image / build` against this branch but tagged `timescaledev/toolkit-builder` instead of `timescaledev/toolkit-builder-test`?

**Comment by zilder** [comment]
Btw I was building this branch locally and was able to get past the `pgrx-bindgen` compilation. There is tons of warnings and errors though regarding [the necessity to implement `ArgAbi` and `RetBox`](https://github.com/pgcentralfoundation/pgrx/releases/tag/v0.12.0). I will take a look at these.

**Comment by Jo0** [comment]
@zilder how are things going? I've been fighting WSL2 in the free time I've had trying to help out with the compilation errors.

**Comment by zilder** [comment]
Hey @Jo0, it took me some time to wrap my head around macros-based code generation in toolkit. With pgrx 0.12+ it seems most issues come from new requirements for `PostgresType` trait implementation. I'm making some progress now, though there are still things I haven't figured out yet.

**Comment by zilder** [comment]
Merged as part of #824
